-- ============================================================
-- V7_06: Nginx 面板模板 (12条)
-- 覆盖: 连接 / 请求 / 上游
-- ============================================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type,
     chart_type, promql, unit, unit_format,
     default_width, default_height, thresholds, options, tags, sort_order, created_at)
VALUES

-- ===================== 连接 (5) =====================

('pt-nginx-01',
 'Active 连接数',
 '当前 Nginx 处于活跃状态的客户端连接数（包括 Reading / Writing / Waiting）',
 'Nginx', '连接', 'nginx_exporter',
 'line',
 'nginx_connections_active{instance=~"{{instance}}"}',
 'count', 'number',
 6, 3,
 '{"warning": 5000, "critical": 10000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Connections", "fillOpacity": 15}',
 '["nginx", "connection", "active"]',
 1, '2025-01-01 00:00:00'),

('pt-nginx-02',
 'Reading 连接数',
 '正在读取客户端请求头的连接数，持续偏高说明请求处理慢或客户端发送慢',
 'Nginx', '连接', 'nginx_exporter',
 'line',
 'nginx_connections_reading{instance=~"{{instance}}"}',
 'count', 'number',
 6, 3,
 '{"warning": 500, "critical": 1000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Reading", "fillOpacity": 10}',
 '["nginx", "connection", "reading"]',
 2, '2025-01-01 00:00:00'),

('pt-nginx-03',
 'Writing 连接数',
 '正在向客户端写入响应的连接数，持续偏高说明下游带宽不足或响应体过大',
 'Nginx', '连接', 'nginx_exporter',
 'line',
 'nginx_connections_writing{instance=~"{{instance}}"}',
 'count', 'number',
 6, 3,
 '{"warning": 500, "critical": 1000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Writing", "fillOpacity": 10}',
 '["nginx", "connection", "writing"]',
 3, '2025-01-01 00:00:00'),

('pt-nginx-04',
 'Waiting 连接数',
 '处于空闲 keep-alive 状态的连接数，数值反映长连接复用情况',
 'Nginx', '连接', 'nginx_exporter',
 'line',
 'nginx_connections_waiting{instance=~"{{instance}}"}',
 'count', 'number',
 6, 3,
 '{"warning": 8000, "critical": 15000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Waiting", "fillOpacity": 10}',
 '["nginx", "connection", "waiting"]',
 4, '2025-01-01 00:00:00'),

('pt-nginx-05',
 'Accepted 连接速率',
 '每秒新接受的客户端连接数，突增可能代表流量激增或攻击',
 'Nginx', '连接', 'nginx_exporter',
 'line',
 'irate(nginx_connections_accepted{instance=~"{{instance}}"}[5m])',
 'conn/s', 'ops',
 6, 3,
 '{"warning": 3000, "critical": 8000}',
 '{"legend": true, "stacked": false, "decimals": 1, "yAxisLabel": "Accept/s", "fillOpacity": 15}',
 '["nginx", "connection", "accept", "rate"]',
 5, '2025-01-01 00:00:00'),

-- ===================== 请求 (4) =====================

('pt-nginx-06',
 '请求总量速率',
 'Nginx 每秒处理的 HTTP 请求总量（所有状态码合计）',
 'Nginx', '请求', 'nginx_exporter',
 'line',
 'irate(nginx_http_requests_total{instance=~"{{instance}}"}[5m])',
 'req/s', 'ops',
 6, 3,
 '{"warning": 10000, "critical": 30000}',
 '{"legend": true, "stacked": false, "decimals": 1, "yAxisLabel": "Requests/s", "fillOpacity": 15}',
 '["nginx", "request", "rate"]',
 6, '2025-01-01 00:00:00'),

('pt-nginx-07',
 'QPS',
 '当前每秒请求数（即时值），适合在大屏或概览中快速查看流量水平',
 'Nginx', '请求', 'nginx_exporter',
 'stat',
 'irate(nginx_http_requests_total{instance=~"{{instance}}"}[5m])',
 'req/s', 'ops',
 3, 2,
 '{"warning": 10000, "critical": 30000}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull", "decimals": 0}',
 '["nginx", "qps", "stat"]',
 7, '2025-01-01 00:00:00'),

('pt-nginx-08',
 'HTTP 状态码分布',
 '按 HTTP 状态码（2xx/3xx/4xx/5xx）分组的每秒响应数，直观展示流量健康度',
 'Nginx', '请求', 'nginx_exporter',
 'line',
 'sum by (status) (irate(nginx_http_responses_total{instance=~"{{instance}}"}[5m]))',
 'resp/s', 'ops',
 6, 3,
 '{}',
 '{"legend": true, "stacked": false, "decimals": 1, "yAxisLabel": "Responses/s", "fillOpacity": 15, "seriesOverrides": [{"match": "5xx", "color": "#F2495C"}, {"match": "4xx", "color": "#FF9830"}, {"match": "2xx", "color": "#73BF69"}]}',
 '["nginx", "status", "http"]',
 8, '2025-01-01 00:00:00'),

('pt-nginx-09',
 'HTTP 错误率',
 '4xx + 5xx 响应占总响应的百分比，持续高于 1% 需排查后端或客户端异常',
 'Nginx', '请求', 'nginx_exporter',
 'gauge',
 '(sum(irate(nginx_http_responses_total{status=~"4..|5..",instance=~"{{instance}}"}[5m])) / sum(irate(nginx_http_responses_total{instance=~"{{instance}}"}[5m]))) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 1, "critical": 5}',
 '{"decimals": 2, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["nginx", "error", "rate"]',
 9, '2025-01-01 00:00:00'),

-- ===================== 上游 (3) =====================

('pt-nginx-10',
 '上游响应时间',
 '上游服务器平均响应时间（从发出请求到收到第一个字节），按上游分组',
 'Nginx', '上游', 'nginx_exporter',
 'line',
 'histogram_quantile(0.95, sum by (upstream, le) (rate(nginx_upstream_request_duration_seconds_bucket{instance=~"{{instance}}"}[5m])))',
 's', 'duration',
 6, 3,
 '{"warning": 0.5, "critical": 2}',
 '{"legend": true, "stacked": false, "decimals": 3, "yAxisLabel": "Latency (s)", "fillOpacity": 10}',
 '["nginx", "upstream", "latency"]',
 10, '2025-01-01 00:00:00'),

('pt-nginx-11',
 '上游活跃连接数',
 '与各上游后端服务器之间的活跃连接数，过高可能导致上游过载',
 'Nginx', '上游', 'nginx_exporter',
 'line',
 'nginx_upstream_connections_active{instance=~"{{instance}}"}',
 'count', 'number',
 6, 3,
 '{"warning": 500, "critical": 1000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Connections", "fillOpacity": 10}',
 '["nginx", "upstream", "connection"]',
 11, '2025-01-01 00:00:00'),

('pt-nginx-12',
 '上游失败率',
 '上游请求失败（502/504/连接超时）占总上游请求的百分比，高于 0.5% 需检查后端健康',
 'Nginx', '上游', 'nginx_exporter',
 'gauge',
 '(sum(irate(nginx_upstream_responses_total{status=~"502|504",instance=~"{{instance}}"}[5m])) / sum(irate(nginx_upstream_responses_total{instance=~"{{instance}}"}[5m]))) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 0.5, "critical": 3}',
 '{"decimals": 2, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["nginx", "upstream", "error", "rate"]',
 12, '2025-01-01 00:00:00');
