-- ============================================
-- V7_04: MySQL (mysqld_exporter) Panel Templates
-- 22 panels covering connections, queries, InnoDB, replication, and misc
-- ============================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type, chart_type,
     promql, unit, unit_format, default_width, default_height,
     thresholds, options, tags, sort_order, created_at)
VALUES

-- ============================================
-- 连接 (4 panels)
-- ============================================

('pt-mysql-01',
 '活跃连接数',
 '当前已建立的客户端连接数，持续接近 max_connections 时需扩容或排查连接泄漏',
 'MySQL', '连接', 'mysqld_exporter', 'gauge',
 'mysql_global_status_threads_connected{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":200,"color":"#faad14","label":"warning"},{"value":300,"color":"#f5222d","label":"critical"}]',
 '{"decimals":0,"colorMode":"thresholds","min":0}',
 '["mysql","connection"]',
 1, '2025-01-01 00:00:00'),

('pt-mysql-02',
 '最大连接使用率',
 '当前连接数占 max_connections 的百分比，超过 80% 应考虑调大上限或优化连接池',
 'MySQL', '连接', 'mysqld_exporter', 'gauge',
 'mysql_global_status_threads_connected{instance=~"$instance"} / mysql_global_variables_max_connections{instance=~"$instance"} * 100',
 '%', 'percent', 6, 3,
 '[{"value":70,"color":"#faad14","label":"warning"},{"value":85,"color":"#f5222d","label":"critical"}]',
 '{"decimals":1,"colorMode":"thresholds","min":0,"max":100}',
 '["mysql","connection"]',
 2, '2025-01-01 00:00:00'),

('pt-mysql-03',
 '线程运行数',
 '当前正在执行查询的线程数，持续过高说明存在慢查询或锁争用',
 'MySQL', '连接', 'mysqld_exporter', 'stat',
 'mysql_global_status_threads_running{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":30,"color":"#faad14","label":"warning"},{"value":60,"color":"#f5222d","label":"critical"}]',
 '{"decimals":0,"colorMode":"thresholds"}',
 '["mysql","connection","thread"]',
 3, '2025-01-01 00:00:00'),

('pt-mysql-04',
 '中断连接率',
 '每秒中断的客户端连接数，包含认证失败、客户端异常断开等',
 'MySQL', '连接', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_aborted_connects{instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[{"value":5,"color":"#faad14","label":"warning"},{"value":20,"color":"#f5222d","label":"critical"}]',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","connection","abort"]',
 4, '2025-01-01 00:00:00'),

-- ============================================
-- 查询 (5 panels)
-- ============================================

('pt-mysql-05',
 'QPS',
 '每秒查询数（Queries Per Second），反映数据库整体负载水平',
 'MySQL', '查询', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_queries{instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[]',
 '{"decimals":1,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","query","qps"]',
 1, '2025-01-01 00:00:00'),

('pt-mysql-06',
 '慢查询率',
 '每秒新增慢查询数，持续上升需检查慢查询日志并优化 SQL',
 'MySQL', '查询', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_slow_queries{instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[{"value":1,"color":"#faad14","label":"warning"},{"value":5,"color":"#f5222d","label":"critical"}]',
 '{"decimals":3,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","query","slow"]',
 2, '2025-01-01 00:00:00'),

('pt-mysql-07',
 '查询类型分布',
 '按 SELECT/INSERT/UPDATE/DELETE 分类的每秒执行次数，帮助分析读写比例',
 'MySQL', '查询', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_commands_total{command=~"select|insert|update|delete",instance=~"$instance"}[5m])',
 'ops', 'ops', 12, 4,
 '[]',
 '{"decimals":1,"fillOpacity":30,"showLegend":true,"stackMode":"normal","legendFormat":"{{command}}"}',
 '["mysql","query","command"]',
 3, '2025-01-01 00:00:00'),

('pt-mysql-08',
 'Com_select 速率',
 '每秒 SELECT 语句执行次数',
 'MySQL', '查询', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_commands_total{command="select",instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[]',
 '{"decimals":1,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","query","select"]',
 4, '2025-01-01 00:00:00'),

('pt-mysql-09',
 'Com_insert 速率',
 '每秒 INSERT 语句执行次数',
 'MySQL', '查询', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_commands_total{command="insert",instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[]',
 '{"decimals":1,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","query","insert"]',
 5, '2025-01-01 00:00:00'),

-- ============================================
-- InnoDB (5 panels)
-- ============================================

('pt-mysql-10',
 '缓冲池命中率',
 'InnoDB Buffer Pool 命中率，低于 99% 表示频繁磁盘读取，应增大 innodb_buffer_pool_size',
 'MySQL', 'InnoDB', 'mysqld_exporter', 'gauge',
 '(1 - rate(mysql_global_status_innodb_buffer_pool_reads{instance=~"$instance"}[5m]) / rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~"$instance"}[5m])) * 100',
 '%', 'percent', 6, 3,
 '[{"value":99,"color":"#52c41a","label":"healthy"},{"value":95,"color":"#faad14","label":"warning"},{"value":90,"color":"#f5222d","label":"critical"}]',
 '{"decimals":2,"colorMode":"thresholds","min":0,"max":100}',
 '["mysql","innodb","buffer_pool"]',
 1, '2025-01-01 00:00:00'),

('pt-mysql-11',
 '缓冲池使用率',
 'InnoDB Buffer Pool 已用页占总页数的百分比',
 'MySQL', 'InnoDB', 'mysqld_exporter', 'gauge',
 '(mysql_global_status_innodb_buffer_pool_pages_total{instance=~"$instance"} - mysql_global_status_innodb_buffer_pool_pages_free{instance=~"$instance"}) / mysql_global_status_innodb_buffer_pool_pages_total{instance=~"$instance"} * 100',
 '%', 'percent', 6, 3,
 '[{"value":85,"color":"#faad14","label":"warning"},{"value":95,"color":"#f5222d","label":"critical"}]',
 '{"decimals":1,"colorMode":"thresholds","min":0,"max":100}',
 '["mysql","innodb","buffer_pool"]',
 2, '2025-01-01 00:00:00'),

('pt-mysql-12',
 '行操作速率',
 'InnoDB 行级操作速率，包含读取、插入、更新、删除，用于评估引擎层负载',
 'MySQL', 'InnoDB', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_innodb_row_ops_total{instance=~"$instance"}[5m])',
 'ops', 'ops', 12, 4,
 '[]',
 '{"decimals":1,"fillOpacity":30,"showLegend":true,"stackMode":"normal","legendFormat":"{{operation}}","queries":[{"promql":"rate(mysql_global_status_innodb_rows_read{instance=~\\"$instance\\"}[5m])","legend":"rows_read"},{"promql":"rate(mysql_global_status_innodb_rows_inserted{instance=~\\"$instance\\"}[5m])","legend":"rows_inserted"},{"promql":"rate(mysql_global_status_innodb_rows_updated{instance=~\\"$instance\\"}[5m])","legend":"rows_updated"},{"promql":"rate(mysql_global_status_innodb_rows_deleted{instance=~\\"$instance\\"}[5m])","legend":"rows_deleted"}]}',
 '["mysql","innodb","row"]',
 3, '2025-01-01 00:00:00'),

('pt-mysql-13',
 'InnoDB 死锁',
 'InnoDB 死锁累计次数，出现时应检查事务隔离级别和加锁顺序',
 'MySQL', 'InnoDB', 'mysqld_exporter', 'stat',
 'mysql_global_status_innodb_deadlocks{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":1,"color":"#faad14","label":"warning"},{"value":10,"color":"#f5222d","label":"critical"}]',
 '{"decimals":0,"colorMode":"thresholds"}',
 '["mysql","innodb","deadlock"]',
 4, '2025-01-01 00:00:00'),

('pt-mysql-14',
 'InnoDB 锁等待',
 '每秒 InnoDB 行锁等待次数，过高说明存在锁争用',
 'MySQL', 'InnoDB', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_innodb_row_lock_waits{instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[{"value":10,"color":"#faad14","label":"warning"},{"value":50,"color":"#f5222d","label":"critical"}]',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","innodb","lock"]',
 5, '2025-01-01 00:00:00'),

-- ============================================
-- 复制 (4 panels)
-- ============================================

('pt-mysql-15',
 '主从延迟',
 '从库复制延迟秒数（Seconds_Behind_Master），超过 10s 需排查复制链路',
 'MySQL', '复制', 'mysqld_exporter', 'gauge',
 'mysql_slave_status_seconds_behind_master{instance=~"$instance"}',
 's', 'duration', 6, 3,
 '[{"value":5,"color":"#faad14","label":"warning"},{"value":30,"color":"#f5222d","label":"critical"}]',
 '{"decimals":0,"colorMode":"thresholds","min":0}',
 '["mysql","replication","lag"]',
 1, '2025-01-01 00:00:00'),

('pt-mysql-16',
 'Slave IO 线程',
 '从库 IO 线程运行状态（1=运行中，0=停止），停止时复制中断',
 'MySQL', '复制', 'mysqld_exporter', 'stat',
 'mysql_slave_status_slave_io_running{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":1,"color":"#52c41a","label":"running"},{"value":0,"color":"#f5222d","label":"stopped"}]',
 '{"decimals":0,"colorMode":"thresholds","mappings":[{"value":1,"text":"Running","color":"#52c41a"},{"value":0,"text":"Stopped","color":"#f5222d"}]}',
 '["mysql","replication","io_thread"]',
 2, '2025-01-01 00:00:00'),

('pt-mysql-17',
 'Slave SQL 线程',
 '从库 SQL 线程运行状态（1=运行中，0=停止），停止时 relay log 不再回放',
 'MySQL', '复制', 'mysqld_exporter', 'stat',
 'mysql_slave_status_slave_sql_running{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":1,"color":"#52c41a","label":"running"},{"value":0,"color":"#f5222d","label":"stopped"}]',
 '{"decimals":0,"colorMode":"thresholds","mappings":[{"value":1,"text":"Running","color":"#52c41a"},{"value":0,"text":"Stopped","color":"#f5222d"}]}',
 '["mysql","replication","sql_thread"]',
 3, '2025-01-01 00:00:00'),

('pt-mysql-18',
 '复制错误',
 '从库最近一次复制错误的错误码，0 表示无错误',
 'MySQL', '复制', 'mysqld_exporter', 'stat',
 'mysql_slave_status_last_errno{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":0,"color":"#52c41a","label":"no_error"},{"value":1,"color":"#f5222d","label":"error"}]',
 '{"decimals":0,"colorMode":"thresholds","mappings":[{"value":0,"text":"No Error","color":"#52c41a"}]}',
 '["mysql","replication","error"]',
 4, '2025-01-01 00:00:00'),

-- ============================================
-- 其他 (4 panels)
-- ============================================

('pt-mysql-19',
 '打开表数',
 '当前打开的表数量，过高可能需要增大 table_open_cache',
 'MySQL', '其他', 'mysqld_exporter', 'line',
 'mysql_global_status_open_tables{instance=~"$instance"}',
 '', 'number', 6, 3,
 '[{"value":2000,"color":"#faad14","label":"warning"},{"value":4000,"color":"#f5222d","label":"critical"}]',
 '{"decimals":0,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","table"]',
 1, '2025-01-01 00:00:00'),

('pt-mysql-20',
 '表锁等待',
 '每秒表级锁等待次数，过高说明存在表锁争用，考虑转为 InnoDB 引擎',
 'MySQL', '其他', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_table_locks_waited{instance=~"$instance"}[5m])',
 'ops', 'ops', 6, 3,
 '[{"value":5,"color":"#faad14","label":"warning"},{"value":20,"color":"#f5222d","label":"critical"}]',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}}"}',
 '["mysql","table","lock"]',
 2, '2025-01-01 00:00:00'),

('pt-mysql-21',
 '网络接收流量',
 'MySQL 每秒接收的网络字节数',
 'MySQL', '其他', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_bytes_received{instance=~"$instance"}[5m])',
 'bytes', 'bytes_iec', 6, 3,
 '[]',
 '{"decimals":1,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}} - received"}',
 '["mysql","network","traffic"]',
 3, '2025-01-01 00:00:00'),

('pt-mysql-22',
 '网络发送流量',
 'MySQL 每秒发送的网络字节数',
 'MySQL', '其他', 'mysqld_exporter', 'line',
 'rate(mysql_global_status_bytes_sent{instance=~"$instance"}[5m])',
 'bytes', 'bytes_iec', 6, 3,
 '[]',
 '{"decimals":1,"fillOpacity":15,"showLegend":true,"stackMode":"none","legendFormat":"{{instance}} - sent"}',
 '["mysql","network","traffic"]',
 4, '2025-01-01 00:00:00');
