-- ============================================================
-- V7_07: Blackbox 探针监控面板模板 (14条)
-- 覆盖: HTTP / DNS / TCP / ICMP
-- ============================================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type,
     chart_type, promql, unit, unit_format,
     default_width, default_height, thresholds, options, tags, sort_order, created_at)
VALUES

-- ===================== HTTP (6) =====================

('pt-blackbox-01',
 '探测成功率',
 '各探测目标的成功率（1 = 成功，0 = 失败），低于 1 表示目标不可达或探测条件不满足',
 '探针监控', 'HTTP', 'blackbox_exporter',
 'gauge',
 'probe_success{instance=~"{{instance}}"}',
 '', 'none',
 3, 3,
 '{"warning": 1, "critical": 0}',
 '{"decimals": 0, "minValue": 0, "maxValue": 1, "thresholdMode": "absolute", "valueMapping": [{"value": 1, "text": "UP", "color": "#73BF69"}, {"value": 0, "text": "DOWN", "color": "#F2495C"}]}',
 '["blackbox", "probe", "success"]',
 1, '2025-01-01 00:00:00'),

('pt-blackbox-02',
 'HTTP 分阶段耗时',
 'HTTP 探测各阶段耗时（DNS 解析、TCP 连接、TLS 握手、服务处理、内容传输），按 phase 分组',
 '探针监控', 'HTTP', 'blackbox_exporter',
 'line',
 'probe_http_duration_seconds{instance=~"{{instance}}"}',
 's', 'duration',
 6, 3,
 '{"warning": 1, "critical": 3}',
 '{"legend": true, "stacked": true, "decimals": 3, "yAxisLabel": "Duration (s)", "fillOpacity": 40, "legendFormat": "{{phase}}"}',
 '["blackbox", "http", "duration", "phase"]',
 2, '2025-01-01 00:00:00'),

('pt-blackbox-03',
 'HTTP 状态码',
 '探测返回的 HTTP 响应状态码，便于快速判断目标 URL 是否正常返回 200',
 '探针监控', 'HTTP', 'blackbox_exporter',
 'stat',
 'probe_http_status_code{instance=~"{{instance}}"}',
 '', 'none',
 3, 2,
 '{"warning": 301, "critical": 400}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull", "decimals": 0, "valueMapping": [{"from": 200, "to": 299, "text": "${__value}", "color": "#73BF69"}, {"from": 300, "to": 399, "text": "${__value}", "color": "#FF9830"}, {"from": 400, "to": 599, "text": "${__value}", "color": "#F2495C"}]}',
 '["blackbox", "http", "status"]',
 3, '2025-01-01 00:00:00'),

('pt-blackbox-04',
 'SSL 证书到期天数',
 'SSL 证书距过期的剩余天数，低于 30 天时需尽快续期',
 '探针监控', 'HTTP', 'blackbox_exporter',
 'gauge',
 '(probe_ssl_earliest_cert_expiry{instance=~"{{instance}}"} - time()) / 86400',
 'days', 'number',
 3, 3,
 '{"warning": 30, "critical": 7}',
 '{"decimals": 0, "minValue": 0, "maxValue": 365, "thresholdMode": "absolute", "reverseThresholds": true}',
 '["blackbox", "ssl", "certificate", "expiry"]',
 4, '2025-01-01 00:00:00'),

('pt-blackbox-05',
 'HTTP 内容长度',
 'HTTP 响应体的字节长度，剧烈变化可能意味着页面内容异常或被劫持',
 '探针监控', 'HTTP', 'blackbox_exporter',
 'stat',
 'probe_http_content_length{instance=~"{{instance}}"}',
 'bytes', 'bytes_iec',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull", "decimals": 0}',
 '["blackbox", "http", "content", "length"]',
 5, '2025-01-01 00:00:00'),

('pt-blackbox-06',
 'HTTP 协议版本',
 '探测使用的 HTTP 协议版本（1.1 = HTTP/1.1, 2 = HTTP/2），可监控协议降级情况',
 '探针监控', 'HTTP', 'blackbox_exporter',
 'stat',
 'probe_http_version{instance=~"{{instance}}"}',
 '', 'none',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull", "decimals": 1, "valueMapping": [{"value": 1, "text": "HTTP/1.0", "color": "#FF9830"}, {"value": 1.1, "text": "HTTP/1.1", "color": "#73BF69"}, {"value": 2, "text": "HTTP/2", "color": "#56A64B"}]}',
 '["blackbox", "http", "version"]',
 6, '2025-01-01 00:00:00'),

-- ===================== DNS (3) =====================

('pt-blackbox-07',
 'DNS 查询耗时',
 'DNS 探测的解析耗时趋势，可用于发现 DNS 服务器性能波动或解析劫持',
 '探针监控', 'DNS', 'blackbox_exporter',
 'line',
 'probe_dns_lookup_time_seconds{instance=~"{{instance}}"}',
 's', 'duration',
 6, 3,
 '{"warning": 0.1, "critical": 0.5}',
 '{"legend": true, "stacked": false, "decimals": 3, "yAxisLabel": "Lookup Time (s)", "fillOpacity": 10}',
 '["blackbox", "dns", "lookup", "time"]',
 7, '2025-01-01 00:00:00'),

('pt-blackbox-08',
 'DNS 查询成功率',
 'DNS 探测的成功率，探测失败可能是 DNS 服务器不可用或域名解析错误',
 '探针监控', 'DNS', 'blackbox_exporter',
 'gauge',
 'probe_success{job=~".*dns.*",instance=~"{{instance}}"}',
 '', 'none',
 3, 3,
 '{"warning": 1, "critical": 0}',
 '{"decimals": 0, "minValue": 0, "maxValue": 1, "thresholdMode": "absolute", "valueMapping": [{"value": 1, "text": "OK", "color": "#73BF69"}, {"value": 0, "text": "FAIL", "color": "#F2495C"}]}',
 '["blackbox", "dns", "success"]',
 8, '2025-01-01 00:00:00'),

('pt-blackbox-09',
 'DNS 解析时间',
 '各探测目标最近一次 DNS 解析耗时（Stat 视图），快速查看解析是否正常',
 '探针监控', 'DNS', 'blackbox_exporter',
 'stat',
 'probe_dns_lookup_time_seconds{instance=~"{{instance}}"}',
 'ms', 'duration',
 3, 2,
 '{"warning": 0.1, "critical": 0.5}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull", "decimals": 1, "unit": "s"}',
 '["blackbox", "dns", "resolve", "stat"]',
 9, '2025-01-01 00:00:00'),

-- ===================== TCP (3) =====================

('pt-blackbox-10',
 'TCP 连接时间',
 'TCP 探测从发起到完成连接的耗时趋势，可检测网络延迟和端口可达性',
 '探针监控', 'TCP', 'blackbox_exporter',
 'line',
 'probe_duration_seconds{job=~".*tcp.*",instance=~"{{instance}}"}',
 's', 'duration',
 6, 3,
 '{"warning": 0.5, "critical": 2}',
 '{"legend": true, "stacked": false, "decimals": 3, "yAxisLabel": "Connect Time (s)", "fillOpacity": 10}',
 '["blackbox", "tcp", "connect", "time"]',
 10, '2025-01-01 00:00:00'),

('pt-blackbox-11',
 'TCP 连接成功率',
 'TCP 端口探测成功率，失败说明端口不可达或防火墙拦截',
 '探针监控', 'TCP', 'blackbox_exporter',
 'gauge',
 'probe_success{job=~".*tcp.*",instance=~"{{instance}}"}',
 '', 'none',
 3, 3,
 '{"warning": 1, "critical": 0}',
 '{"decimals": 0, "minValue": 0, "maxValue": 1, "thresholdMode": "absolute", "valueMapping": [{"value": 1, "text": "OK", "color": "#73BF69"}, {"value": 0, "text": "FAIL", "color": "#F2495C"}]}',
 '["blackbox", "tcp", "success"]',
 11, '2025-01-01 00:00:00'),

('pt-blackbox-12',
 'TCP 握手耗时',
 '各探测目标最近一次 TCP 握手耗时（Stat 视图），快速发现网络连通性问题',
 '探针监控', 'TCP', 'blackbox_exporter',
 'stat',
 'probe_duration_seconds{job=~".*tcp.*",instance=~"{{instance}}"}',
 'ms', 'duration',
 3, 2,
 '{"warning": 0.3, "critical": 1}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull", "decimals": 1, "unit": "s"}',
 '["blackbox", "tcp", "handshake", "stat"]',
 12, '2025-01-01 00:00:00'),

-- ===================== ICMP (2) =====================

('pt-blackbox-13',
 'ICMP 延迟',
 'ICMP 探测各阶段延迟（setup / rtt），按 phase 分组展示网络延迟详情',
 '探针监控', 'ICMP', 'blackbox_exporter',
 'line',
 'probe_icmp_duration_seconds{instance=~"{{instance}}"}',
 's', 'duration',
 6, 3,
 '{"warning": 0.1, "critical": 0.5}',
 '{"legend": true, "stacked": false, "decimals": 3, "yAxisLabel": "Latency (s)", "fillOpacity": 15, "legendFormat": "{{phase}}"}',
 '["blackbox", "icmp", "latency", "phase"]',
 13, '2025-01-01 00:00:00'),

('pt-blackbox-14',
 'ICMP 丢包率',
 'ICMP 探测的成功率反转，显示丢包百分比，持续丢包需检查网络链路质量',
 '探针监控', 'ICMP', 'blackbox_exporter',
 'gauge',
 '(1 - probe_success{job=~".*icmp.*",instance=~"{{instance}}"}) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 5, "critical": 20}',
 '{"decimals": 1, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["blackbox", "icmp", "packet", "loss"]',
 14, '2025-01-01 00:00:00');
