-- ============================================================
-- V7_09: JVM 监控面板模板 (15条)
-- 覆盖: 堆内存 / GC / 非堆内存 / 线程 / 类加载
-- ============================================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type,
     chart_type, promql, unit, unit_format,
     default_width, default_height, thresholds, options, tags, sort_order, created_at)
VALUES

-- ===================== 堆内存 (3) =====================

('pt-jvm-01',
 '堆内存使用量',
 'JVM 堆内存实际使用量，按实例分组，持续增长可能存在内存泄漏',
 'JVM', '堆内存', 'jmx_exporter',
 'line',
 'jvm_memory_bytes_used{area="heap",instance=~"{{instance}}"}',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 1073741824, "critical": 2147483648}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Heap Used", "fillOpacity": 15}',
 '["jvm", "heap", "memory"]',
 1, '2025-01-01 00:00:00'),

('pt-jvm-02',
 '堆内存最大值',
 'JVM 堆内存配置的最大值（-Xmx），用于评估内存容量上限',
 'JVM', '堆内存', 'jmx_exporter',
 'stat',
 'jvm_memory_bytes_max{area="heap",instance=~"{{instance}}"}',
 'bytes', 'bytes_iec',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["jvm", "heap", "max"]',
 2, '2025-01-01 00:00:00'),

('pt-jvm-03',
 '堆内存使用率',
 'JVM 堆内存使用量占最大堆内存的百分比，接近 100% 时极易发生 OOM',
 'JVM', '堆内存', 'jmx_exporter',
 'gauge',
 'jvm_memory_bytes_used{area="heap",instance=~"{{instance}}"} / jvm_memory_bytes_max{area="heap",instance=~"{{instance}}"} * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 70, "critical": 90}',
 '{"decimals": 1, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["jvm", "heap", "usage"]',
 3, '2025-01-01 00:00:00'),

-- ===================== GC (4) =====================

('pt-jvm-04',
 'GC 暂停时间',
 'GC 暂停总耗时的速率，按 GC 动作分组，反映 GC 对应用的影响程度',
 'JVM', 'GC', 'jmx_exporter',
 'line',
 'rate(jvm_gc_pause_seconds_sum{instance=~"{{instance}}"}[5m])',
 's', 'duration',
 6, 3,
 '{"warning": 0.1, "critical": 0.5}',
 '{"legend": true, "stacked": false, "decimals": 4, "yAxisLabel": "GC Pause (s/s)", "fillOpacity": 10}',
 '["jvm", "gc", "pause"]',
 4, '2025-01-01 00:00:00'),

('pt-jvm-05',
 'GC 次数',
 '每秒 GC 发生次数，按 GC 动作分组，频繁 GC 说明内存压力较大',
 'JVM', 'GC', 'jmx_exporter',
 'line',
 'rate(jvm_gc_pause_seconds_count{instance=~"{{instance}}"}[5m])',
 'ops', 'short',
 6, 3,
 '{"warning": 5, "critical": 20}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "GC/s", "fillOpacity": 10}',
 '["jvm", "gc", "count"]',
 5, '2025-01-01 00:00:00'),

('pt-jvm-06',
 'Young GC 耗时',
 '年轻代 GC（Minor GC）的暂停耗时速率，正常应在毫秒级',
 'JVM', 'GC', 'jmx_exporter',
 'line',
 'rate(jvm_gc_pause_seconds_sum{action="end of minor GC",instance=~"{{instance}}"}[5m])',
 's', 'duration',
 6, 3,
 '{"warning": 0.05, "critical": 0.2}',
 '{"legend": true, "stacked": false, "decimals": 4, "yAxisLabel": "Young GC (s/s)", "fillOpacity": 10}',
 '["jvm", "gc", "young"]',
 6, '2025-01-01 00:00:00'),

('pt-jvm-07',
 'Full GC 耗时',
 '老年代 GC（Major/Full GC）的暂停耗时速率，Full GC 会导致长时间 STW',
 'JVM', 'GC', 'jmx_exporter',
 'line',
 'rate(jvm_gc_pause_seconds_sum{action="end of major GC",instance=~"{{instance}}"}[5m])',
 's', 'duration',
 6, 3,
 '{"warning": 0.1, "critical": 1}',
 '{"legend": true, "stacked": false, "decimals": 4, "yAxisLabel": "Full GC (s/s)", "fillOpacity": 10}',
 '["jvm", "gc", "full"]',
 7, '2025-01-01 00:00:00'),

-- ===================== 非堆内存 (3) =====================

('pt-jvm-08',
 'Metaspace 使用量',
 'JVM Metaspace 区域的内存使用量，类加载过多会导致 Metaspace 溢出',
 'JVM', '非堆内存', 'jmx_exporter',
 'line',
 'jvm_memory_bytes_used{area="nonheap",id="Metaspace",instance=~"{{instance}}"}',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 268435456, "critical": 536870912}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Metaspace", "fillOpacity": 15}',
 '["jvm", "metaspace", "nonheap"]',
 8, '2025-01-01 00:00:00'),

('pt-jvm-09',
 'CodeCache 使用量',
 'JVM CodeCache 区域的内存使用量，JIT 编译后的本地代码存放于此',
 'JVM', '非堆内存', 'jmx_exporter',
 'line',
 'jvm_memory_bytes_used{area="nonheap",id=~"Code.*Cache.*",instance=~"{{instance}}"}',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 134217728, "critical": 234881024}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "CodeCache", "fillOpacity": 15}',
 '["jvm", "codecache", "nonheap"]',
 9, '2025-01-01 00:00:00'),

('pt-jvm-10',
 '非堆内存总量',
 'JVM 非堆内存总使用量，包含 Metaspace、CodeCache、Compressed Class Space 等',
 'JVM', '非堆内存', 'jmx_exporter',
 'stat',
 'sum(jvm_memory_bytes_used{area="nonheap",instance=~"{{instance}}"})',
 'bytes', 'bytes_iec',
 3, 2,
 '{"warning": 536870912, "critical": 1073741824}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["jvm", "nonheap", "total"]',
 10, '2025-01-01 00:00:00'),

-- ===================== 线程 (3) =====================

('pt-jvm-11',
 '存活线程数',
 'JVM 当前存活的线程总数，持续上升可能存在线程泄漏',
 'JVM', '线程', 'jmx_exporter',
 'line',
 'jvm_threads_current{instance=~"{{instance}}"}',
 'count', 'short',
 6, 3,
 '{"warning": 500, "critical": 1000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Threads", "fillOpacity": 10}',
 '["jvm", "threads", "current"]',
 11, '2025-01-01 00:00:00'),

('pt-jvm-12',
 '守护线程数',
 'JVM 守护线程（Daemon Thread）数量，随主线程退出自动终止',
 'JVM', '线程', 'jmx_exporter',
 'stat',
 'jvm_threads_daemon{instance=~"{{instance}}"}',
 'count', 'short',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["jvm", "threads", "daemon"]',
 12, '2025-01-01 00:00:00'),

('pt-jvm-13',
 '线程峰值',
 'JVM 启动以来线程数的历史峰值，用于评估最大线程使用情况',
 'JVM', '线程', 'jmx_exporter',
 'stat',
 'jvm_threads_peak{instance=~"{{instance}}"}',
 'count', 'short',
 3, 2,
 '{"warning": 500, "critical": 1000}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["jvm", "threads", "peak"]',
 13, '2025-01-01 00:00:00'),

-- ===================== 类加载 (2) =====================

('pt-jvm-14',
 '已加载类数',
 'JVM 当前已加载的 Class 数量，持续增长需排查是否存在类加载器泄漏',
 'JVM', '类加载', 'jmx_exporter',
 'stat',
 'jvm_classes_loaded{instance=~"{{instance}}"}',
 'count', 'short',
 3, 2,
 '{"warning": 20000, "critical": 50000}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["jvm", "classes", "loaded"]',
 14, '2025-01-01 00:00:00'),

('pt-jvm-15',
 '类加载速率',
 '每秒加载的类数量速率，部署或热加载时出现尖峰属正常现象',
 'JVM', '类加载', 'jmx_exporter',
 'line',
 'rate(jvm_classes_loaded_total{instance=~"{{instance}}"}[5m])',
 'ops', 'short',
 6, 3,
 '{"warning": 10, "critical": 50}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Classes/s", "fillOpacity": 10}',
 '["jvm", "classes", "rate"]',
 15, '2025-01-01 00:00:00');
