-- ============================================================
-- V7_02: cAdvisor 容器监控面板模板 (20条)
-- 覆盖: 容器CPU / 容器内存 / 容器网络 / 容器存储 / Pod状态
-- ============================================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type,
     chart_type, promql, unit, unit_format,
     default_width, default_height, thresholds, options, tags, sort_order, created_at)
VALUES

-- ===================== 容器CPU (5) =====================

('pt-cadvisor-01',
 '容器 CPU 使用率',
 '每个容器的 CPU 使用率（多核合计），按容器名称分组',
 '容器监控', 'CPU', 'cadvisor',
 'line',
 'sum by (name) (rate(container_cpu_usage_seconds_total{image!="",name=~"{{container}}"}[5m])) * 100',
 '%', 'percent',
 6, 3,
 '{"warning": 60, "critical": 85}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "CPU %", "fillOpacity": 15}',
 '["cpu", "container", "cadvisor"]',
 1, '2025-01-01 00:00:00'),

('pt-cadvisor-02',
 '容器 CPU 限制使用率',
 '容器实际 CPU 用量占 CPU Limit 配额的百分比，超过 100% 表示可能被节流',
 '容器监控', 'CPU', 'cadvisor',
 'gauge',
 'sum by (name) (rate(container_cpu_usage_seconds_total{image!="",name=~"{{container}}"}[5m])) / (sum by (name) (container_spec_cpu_quota{image!="",name=~"{{container}}"} / container_spec_cpu_period{image!="",name=~"{{container}}"})) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 70, "critical": 90}',
 '{"decimals": 1, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["cpu", "quota", "cadvisor"]',
 2, '2025-01-01 00:00:00'),

('pt-cadvisor-03',
 'CPU 节流率',
 'CFS 调度器节流周期占总周期的比率，持续高于 0 说明 CPU Limit 不足',
 '容器监控', 'CPU', 'cadvisor',
 'line',
 'sum by (name) (rate(container_cpu_cfs_throttled_periods_total{image!="",name=~"{{container}}"}[5m])) / sum by (name) (rate(container_cpu_cfs_periods_total{image!="",name=~"{{container}}"}[5m])) * 100',
 '%', 'percent',
 6, 3,
 '{"warning": 25, "critical": 50}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Throttle %", "fillOpacity": 10}',
 '["cpu", "throttle", "cadvisor"]',
 3, '2025-01-01 00:00:00'),

('pt-cadvisor-04',
 '容器 CPU 用户态',
 '容器在用户态消耗的 CPU 时间速率，反映应用代码的计算负载',
 '容器监控', 'CPU', 'cadvisor',
 'line',
 'sum by (name) (rate(container_cpu_user_seconds_total{image!="",name=~"{{container}}"}[5m])) * 100',
 '%', 'percent',
 6, 3,
 '{"warning": 50, "critical": 80}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "User CPU %", "fillOpacity": 10}',
 '["cpu", "user", "cadvisor"]',
 4, '2025-01-01 00:00:00'),

('pt-cadvisor-05',
 '容器 CPU 系统态',
 '容器在内核态消耗的 CPU 时间速率，过高可能意味着频繁的系统调用或 I/O',
 '容器监控', 'CPU', 'cadvisor',
 'line',
 'sum by (name) (rate(container_cpu_system_seconds_total{image!="",name=~"{{container}}"}[5m])) * 100',
 '%', 'percent',
 6, 3,
 '{"warning": 30, "critical": 60}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "System CPU %", "fillOpacity": 10}',
 '["cpu", "system", "cadvisor"]',
 5, '2025-01-01 00:00:00'),

-- ===================== 容器内存 (5) =====================

('pt-cadvisor-06',
 '容器内存使用量',
 '容器的 RSS + Cache 总内存使用量（container_memory_usage_bytes）',
 '容器监控', '内存', 'cadvisor',
 'line',
 'sum by (name) (container_memory_usage_bytes{image!="",name=~"{{container}}"})',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 1073741824, "critical": 2147483648}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Memory", "fillOpacity": 15}',
 '["memory", "container", "cadvisor"]',
 6, '2025-01-01 00:00:00'),

('pt-cadvisor-07',
 '容器 WorkingSet',
 '容器的 Working Set 大小，代表不可回收的活跃内存，是 OOM 判定依据',
 '容器监控', '内存', 'cadvisor',
 'line',
 'sum by (name) (container_memory_working_set_bytes{image!="",name=~"{{container}}"})',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 858993459, "critical": 1717986918}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Working Set", "fillOpacity": 15}',
 '["memory", "workingset", "cadvisor"]',
 7, '2025-01-01 00:00:00'),

('pt-cadvisor-08',
 '内存使用率',
 '容器 Working Set 占内存 Limit 的百分比，接近 100% 时极易 OOM',
 '容器监控', '内存', 'cadvisor',
 'gauge',
 'sum by (name) (container_memory_working_set_bytes{image!="",name=~"{{container}}"}) / sum by (name) (container_spec_memory_limit_bytes{image!="",name=~"{{container}}"} > 0) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 70, "critical": 90}',
 '{"decimals": 1, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["memory", "usage", "cadvisor"]',
 8, '2025-01-01 00:00:00'),

('pt-cadvisor-09',
 '容器内存限制',
 '容器 cgroup 的内存 Limit 配置值，0 或极大值表示未设限',
 '容器监控', '内存', 'cadvisor',
 'stat',
 'sum by (name) (container_spec_memory_limit_bytes{image!="",name=~"{{container}}"} > 0)',
 'bytes', 'bytes_iec',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["memory", "limit", "cadvisor"]',
 9, '2025-01-01 00:00:00'),

('pt-cadvisor-10',
 'OOM Kill 计数',
 '容器因内存不足被 OOM Killer 终止的累计次数',
 '容器监控', '内存', 'cadvisor',
 'stat',
 'sum by (name) (container_oom_events_total{image!="",name=~"{{container}}"})',
 'count', 'number',
 3, 2,
 '{"warning": 1, "critical": 5}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["memory", "oom", "cadvisor"]',
 10, '2025-01-01 00:00:00'),

-- ===================== 容器网络 (4) =====================

('pt-cadvisor-11',
 '网络接收速率',
 '容器每秒接收的网络流量，按容器名称分组',
 '容器监控', '网络', 'cadvisor',
 'line',
 'sum by (name) (rate(container_network_receive_bytes_total{image!="",name=~"{{container}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 52428800, "critical": 104857600}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Receive (Bps)", "fillOpacity": 15}',
 '["network", "receive", "cadvisor"]',
 11, '2025-01-01 00:00:00'),

('pt-cadvisor-12',
 '网络发送速率',
 '容器每秒发送的网络流量，按容器名称分组',
 '容器监控', '网络', 'cadvisor',
 'line',
 'sum by (name) (rate(container_network_transmit_bytes_total{image!="",name=~"{{container}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 52428800, "critical": 104857600}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Transmit (Bps)", "fillOpacity": 15}',
 '["network", "transmit", "cadvisor"]',
 12, '2025-01-01 00:00:00'),

('pt-cadvisor-13',
 '网络错误',
 '容器网络收发错误速率，持续非零需排查网卡或驱动问题',
 '容器监控', '网络', 'cadvisor',
 'line',
 'sum by (name) (rate(container_network_receive_errors_total{image!="",name=~"{{container}}"}[5m]) + rate(container_network_transmit_errors_total{image!="",name=~"{{container}}"}[5m]))',
 'ops', 'ops',
 6, 3,
 '{"warning": 1, "critical": 10}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Errors/s", "fillOpacity": 10}',
 '["network", "errors", "cadvisor"]',
 13, '2025-01-01 00:00:00'),

('pt-cadvisor-14',
 '网络丢包',
 '容器网络收发丢包速率，丢包持续出现可能导致应用超时',
 '容器监控', '网络', 'cadvisor',
 'line',
 'sum by (name) (rate(container_network_receive_packets_dropped_total{image!="",name=~"{{container}}"}[5m]) + rate(container_network_transmit_packets_dropped_total{image!="",name=~"{{container}}"}[5m]))',
 'ops', 'ops',
 6, 3,
 '{"warning": 1, "critical": 10}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Drops/s", "fillOpacity": 10}',
 '["network", "drops", "cadvisor"]',
 14, '2025-01-01 00:00:00'),

-- ===================== 容器存储 (4) =====================

('pt-cadvisor-15',
 '磁盘读取速率',
 '容器块设备每秒读取字节数',
 '容器监控', '存储', 'cadvisor',
 'line',
 'sum by (name) (rate(container_fs_reads_bytes_total{image!="",name=~"{{container}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 52428800, "critical": 104857600}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Read (Bps)", "fillOpacity": 15}',
 '["disk", "read", "cadvisor"]',
 15, '2025-01-01 00:00:00'),

('pt-cadvisor-16',
 '磁盘写入速率',
 '容器块设备每秒写入字节数',
 '容器监控', '存储', 'cadvisor',
 'line',
 'sum by (name) (rate(container_fs_writes_bytes_total{image!="",name=~"{{container}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 52428800, "critical": 104857600}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Write (Bps)", "fillOpacity": 15}',
 '["disk", "write", "cadvisor"]',
 16, '2025-01-01 00:00:00'),

('pt-cadvisor-17',
 '文件系统使用量',
 '容器根文件系统已使用空间（overlay fs 层面）',
 '容器监控', '存储', 'cadvisor',
 'bar',
 'sum by (name) (container_fs_usage_bytes{image!="",name=~"{{container}}"})',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 5368709120, "critical": 10737418240}',
 '{"legend": true, "orientation": "horizontal", "showValue": true, "decimals": 2}',
 '["disk", "filesystem", "cadvisor"]',
 17, '2025-01-01 00:00:00'),

('pt-cadvisor-18',
 '文件系统使用率',
 '容器根文件系统已用空间占总空间的百分比',
 '容器监控', '存储', 'cadvisor',
 'gauge',
 'sum by (name) (container_fs_usage_bytes{image!="",name=~"{{container}}"}) / sum by (name) (container_fs_limit_bytes{image!="",name=~"{{container}}"} > 0) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 70, "critical": 85}',
 '{"decimals": 1, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["disk", "filesystem", "usage", "cadvisor"]',
 18, '2025-01-01 00:00:00'),

-- ===================== Pod 状态 (2) =====================

('pt-cadvisor-19',
 'Pod 重启次数',
 'Pod 内容器的累计重启次数，频繁重启需关注 CrashLoopBackOff',
 '容器监控', 'Pod', 'cadvisor',
 'line',
 'sum by (pod, container) (kube_pod_container_status_restarts_total{pod=~"{{pod}}"})',
 'count', 'number',
 6, 3,
 '{"warning": 3, "critical": 10}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Restarts", "fillOpacity": 10}',
 '["pod", "restart", "kubernetes"]',
 19, '2025-01-01 00:00:00'),

('pt-cadvisor-20',
 '容器状态概览',
 '展示 Pod 内各容器的运行状态（Running / Waiting / Terminated），便于快速定位异常容器',
 '容器监控', 'Pod', 'cadvisor',
 'table',
 'kube_pod_container_status_running{pod=~"{{pod}}"} * 1 + kube_pod_container_status_waiting{pod=~"{{pod}}"} * 2 + kube_pod_container_status_terminated{pod=~"{{pod}}"} * 3',
 '', 'none',
 12, 4,
 '{}',
 '{"columns": ["pod", "container", "Value"], "valueMapping": [{"value": 1, "text": "Running", "color": "#73BF69"}, {"value": 2, "text": "Waiting", "color": "#FF9830"}, {"value": 3, "text": "Terminated", "color": "#F2495C"}], "showHeader": true, "filterable": true}',
 '["pod", "status", "kubernetes"]',
 20, '2025-01-01 00:00:00');
