-- ============================================================================
-- V7_01: Panel Templates - Node Exporter (node_exporter)
-- 40 panel templates covering CPU, Memory, Disk, Network, System
-- Table: prom_panel_template
-- ============================================================================

INSERT IGNORE INTO prom_panel_template
  (id, name, description, category, sub_category, exporter_type, chart_type,
   promql, unit, unit_format, default_width, default_height,
   thresholds, options, tags, sort_order, created_at)
VALUES

-- ============================================================================
-- CPU (sub_category: 'CPU', panels 01-08)
-- ============================================================================

('pt-node-01', 'CPU 使用率',
 '所有CPU核心的平均使用率，100%减去空闲比例',
 '主机监控', 'CPU', 'node_exporter', 'line',
 '100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle",instance=~"{{instance}}"}[5m])) * 100)',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":80,"color":"orange"},{"value":95,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["cpu","usage","node"]',
 1, '2025-01-01 00:00:00'),

('pt-node-02', 'CPU 各模式占比',
 'CPU各运行模式的时间占比，包括user/system/iowait/idle/nice/steal',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'avg by(mode,instance)(irate(node_cpu_seconds_total{instance=~"{{instance}}",mode=~"user|system|iowait|idle|nice|steal"}[5m])) * 100',
 '%', 'percent', 12, 4,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":30,"showLegend":true,"stackMode":"stacked","colorMode":"palette"}',
 '["cpu","mode","breakdown"]',
 2, '2025-01-01 00:00:00'),

('pt-node-03', '系统负载',
 '1分钟、5分钟、15分钟系统平均负载',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'node_load1{instance=~"{{instance}}"}',
 '', 'number', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":4,"color":"orange"},{"value":8,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["node_load5{instance=~\\"{{instance}}\\"}", "node_load15{instance=~\\"{{instance}}\\"}"]}',
 '["cpu","load","system"]',
 3, '2025-01-01 00:00:00'),

('pt-node-04', 'CPU iowait',
 'CPU等待I/O完成的时间占比，过高说明存在磁盘瓶颈',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'avg by(instance)(irate(node_cpu_seconds_total{mode="iowait",instance=~"{{instance}}"}[5m])) * 100',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":10,"color":"orange"},{"value":30,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["cpu","iowait","io"]',
 4, '2025-01-01 00:00:00'),

('pt-node-05', '上下文切换率',
 '每秒CPU上下文切换次数，过高会导致性能下降',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'irate(node_context_switches_total{instance=~"{{instance}}"}[5m])',
 'ops', 'ops', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":50000,"color":"orange"},{"value":100000,"color":"red"}]}',
 '{"decimals":0,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["cpu","context_switch","kernel"]',
 5, '2025-01-01 00:00:00'),

('pt-node-06', 'CPU 用户态使用率',
 'CPU在用户态（user mode）的时间占比',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'avg by(instance)(irate(node_cpu_seconds_total{mode="user",instance=~"{{instance}}"}[5m])) * 100',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":70,"color":"orange"},{"value":90,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["cpu","user","mode"]',
 6, '2025-01-01 00:00:00'),

('pt-node-07', 'CPU 系统态使用率',
 'CPU在系统态（system/kernel mode）的时间占比',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'avg by(instance)(irate(node_cpu_seconds_total{mode="system",instance=~"{{instance}}"}[5m])) * 100',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":30,"color":"orange"},{"value":60,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["cpu","system","kernel"]',
 7, '2025-01-01 00:00:00'),

('pt-node-08', 'CPU steal 时间',
 '虚拟机被宿主机hypervisor抢占的CPU时间占比，仅在虚拟化环境中有意义',
 '主机监控', 'CPU', 'node_exporter', 'line',
 'avg by(instance)(irate(node_cpu_seconds_total{mode="steal",instance=~"{{instance}}"}[5m])) * 100',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":5,"color":"orange"},{"value":15,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["cpu","steal","vm"]',
 8, '2025-01-01 00:00:00'),

-- ============================================================================
-- Memory (sub_category: '内存', panels 09-16)
-- ============================================================================

('pt-node-09', '内存使用率',
 '已使用内存占总内存的百分比',
 '主机监控', '内存', 'node_exporter', 'gauge',
 '(1 - node_memory_MemAvailable_bytes{instance=~"{{instance}}"} / node_memory_MemTotal_bytes{instance=~"{{instance}}"}) * 100',
 '%', 'percent', 4, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":85,"color":"orange"},{"value":95,"color":"red"}]}',
 '{"decimals":1,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["memory","usage","ram"]',
 9, '2025-01-01 00:00:00'),

('pt-node-10', '内存使用详情',
 '内存各组成部分：已使用、buffers、cached、空闲，堆叠显示',
 '主机监控', '内存', 'node_exporter', 'line',
 'node_memory_MemTotal_bytes{instance=~"{{instance}}"} - node_memory_MemFree_bytes{instance=~"{{instance}}"} - node_memory_Buffers_bytes{instance=~"{{instance}}"} - node_memory_Cached_bytes{instance=~"{{instance}}"}',
 'bytes', 'bytes_iec', 12, 4,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":40,"showLegend":true,"stackMode":"stacked","colorMode":"palette","extraQueries":["node_memory_Buffers_bytes{instance=~\\"{{instance}}\\"}", "node_memory_Cached_bytes{instance=~\\"{{instance}}\\"}", "node_memory_MemFree_bytes{instance=~\\"{{instance}}\\"}"]}',
 '["memory","detail","stacked"]',
 10, '2025-01-01 00:00:00'),

('pt-node-11', 'Swap 使用率',
 'Swap空间使用百分比',
 '主机监控', '内存', 'node_exporter', 'gauge',
 '(1 - node_memory_SwapFree_bytes{instance=~"{{instance}}"} / node_memory_SwapTotal_bytes{instance=~"{{instance}}"}) * 100',
 '%', 'percent', 4, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":50,"color":"orange"},{"value":80,"color":"red"}]}',
 '{"decimals":1,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["memory","swap","usage"]',
 11, '2025-01-01 00:00:00'),

('pt-node-12', 'Swap 使用详情',
 'Swap空间的使用量和空闲量随时间变化趋势',
 '主机监控', '内存', 'node_exporter', 'line',
 'node_memory_SwapTotal_bytes{instance=~"{{instance}}"} - node_memory_SwapFree_bytes{instance=~"{{instance}}"}',
 'bytes', 'bytes_iec', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["node_memory_SwapFree_bytes{instance=~\\"{{instance}}\\"}"]}',
 '["memory","swap","detail"]',
 12, '2025-01-01 00:00:00'),

('pt-node-13', '内存可用量',
 '当前可用内存大小（MemAvailable），包含空闲和可回收部分',
 '主机监控', '内存', 'node_exporter', 'stat',
 'node_memory_MemAvailable_bytes{instance=~"{{instance}}"}',
 'bytes', 'bytes_iec', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"red"},{"value":1073741824,"color":"orange"},{"value":4294967296,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["memory","available","stat"]',
 13, '2025-01-01 00:00:00'),

('pt-node-14', '内存总量',
 '主机物理内存总量',
 '主机监控', '内存', 'node_exporter', 'stat',
 'node_memory_MemTotal_bytes{instance=~"{{instance}}"}',
 'bytes', 'bytes_iec', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"blue"}]}',
 '{"decimals":2,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"fixed"}',
 '["memory","total","stat"]',
 14, '2025-01-01 00:00:00'),

('pt-node-15', '页错误率',
 '每秒内存页错误（page fault）次数，包含major和minor fault',
 '主机监控', '内存', 'node_exporter', 'line',
 'irate(node_vmstat_pgfault{instance=~"{{instance}}"}[5m])',
 'ops', 'ops', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":5000,"color":"orange"},{"value":20000,"color":"red"}]}',
 '{"decimals":0,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["memory","pagefault","vm"]',
 15, '2025-01-01 00:00:00'),

('pt-node-16', '内存使用趋势',
 '内存使用率的时间变化趋势，用于预测内存增长',
 '主机监控', '内存', 'node_exporter', 'line',
 '(1 - node_memory_MemAvailable_bytes{instance=~"{{instance}}"} / node_memory_MemTotal_bytes{instance=~"{{instance}}"}) * 100',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":85,"color":"orange"},{"value":95,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":20,"showLegend":true,"stackMode":"none","colorMode":"gradient"}',
 '["memory","trend","usage"]',
 16, '2025-01-01 00:00:00'),

-- ============================================================================
-- Disk (sub_category: '磁盘', panels 17-24)
-- ============================================================================

('pt-node-17', '磁盘使用率',
 '各挂载点的磁盘空间使用百分比',
 '主机监控', '磁盘', 'node_exporter', 'bar',
 '(1 - node_filesystem_avail_bytes{instance=~"{{instance}}",fstype!~"tmpfs|overlay|squashfs"} / node_filesystem_size_bytes{instance=~"{{instance}}",fstype!~"tmpfs|overlay|squashfs"}) * 100',
 '%', 'percent', 6, 4,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":80,"color":"orange"},{"value":90,"color":"red"}]}',
 '{"decimals":1,"fillOpacity":80,"showLegend":true,"stackMode":"none","colorMode":"thresholds"}',
 '["disk","usage","filesystem"]',
 17, '2025-01-01 00:00:00'),

('pt-node-18', '磁盘 IOPS',
 '每秒磁盘读写操作次数（IOPS）',
 '主机监控', '磁盘', 'node_exporter', 'line',
 'irate(node_disk_reads_completed_total{instance=~"{{instance}}",device!~"dm-.*"}[5m])',
 'iops', 'ops', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":1,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["irate(node_disk_writes_completed_total{instance=~\\"{{instance}}\\",device!~\\"dm-.*\\"}[5m])"]}',
 '["disk","iops","io"]',
 18, '2025-01-01 00:00:00'),

('pt-node-19', '磁盘吞吐量',
 '磁盘读写字节吞吐量',
 '主机监控', '磁盘', 'node_exporter', 'line',
 'irate(node_disk_read_bytes_total{instance=~"{{instance}}",device!~"dm-.*"}[5m])',
 'bytes/s', 'bytes_iec', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["irate(node_disk_written_bytes_total{instance=~\\"{{instance}}\\",device!~\\"dm-.*\\"}[5m])"]}',
 '["disk","throughput","io"]',
 19, '2025-01-01 00:00:00'),

('pt-node-20', '磁盘 I/O 延迟',
 '磁盘I/O平均延迟时间（毫秒），基于io_time计算',
 '主机监控', '磁盘', 'node_exporter', 'line',
 'irate(node_disk_io_time_seconds_total{instance=~"{{instance}}",device!~"dm-.*"}[5m]) * 1000',
 'ms', 'duration_ms', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":50,"color":"orange"},{"value":200,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["disk","latency","io"]',
 20, '2025-01-01 00:00:00'),

('pt-node-21', 'inode 使用率',
 '各挂载点的inode使用百分比',
 '主机监控', '磁盘', 'node_exporter', 'bar',
 '(1 - node_filesystem_files_free{instance=~"{{instance}}",fstype!~"tmpfs|overlay|squashfs"} / node_filesystem_files{instance=~"{{instance}}",fstype!~"tmpfs|overlay|squashfs"}) * 100',
 '%', 'percent', 6, 4,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":70,"color":"orange"},{"value":90,"color":"red"}]}',
 '{"decimals":1,"fillOpacity":80,"showLegend":true,"stackMode":"none","colorMode":"thresholds"}',
 '["disk","inode","filesystem"]',
 21, '2025-01-01 00:00:00'),

('pt-node-22', '磁盘读吞吐',
 '磁盘读取字节速率',
 '主机监控', '磁盘', 'node_exporter', 'line',
 'irate(node_disk_read_bytes_total{instance=~"{{instance}}",device!~"dm-.*"}[5m])',
 'bytes/s', 'bytes_iec', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["disk","read","throughput"]',
 22, '2025-01-01 00:00:00'),

('pt-node-23', '磁盘写吞吐',
 '磁盘写入字节速率',
 '主机监控', '磁盘', 'node_exporter', 'line',
 'irate(node_disk_written_bytes_total{instance=~"{{instance}}",device!~"dm-.*"}[5m])',
 'bytes/s', 'bytes_iec', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["disk","write","throughput"]',
 23, '2025-01-01 00:00:00'),

('pt-node-24', '磁盘 I/O 使用率',
 '磁盘I/O忙碌时间占比，反映磁盘繁忙程度',
 '主机监控', '磁盘', 'node_exporter', 'line',
 'irate(node_disk_io_time_seconds_total{instance=~"{{instance}}",device!~"dm-.*"}[5m]) * 100',
 '%', 'percent', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":60,"color":"orange"},{"value":90,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["disk","io_util","busy"]',
 24, '2025-01-01 00:00:00'),

-- ============================================================================
-- Network (sub_category: '网络', panels 25-32)
-- ============================================================================

('pt-node-25', '网络接收带宽',
 '网络接口接收数据速率（bits/s），排除lo和veth设备',
 '主机监控', '网络', 'node_exporter', 'line',
 'irate(node_network_receive_bytes_total{instance=~"{{instance}}",device!~"lo|veth.*|docker.*|br-.*"}[5m]) * 8',
 'bps', 'bps', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["network","receive","bandwidth"]',
 25, '2025-01-01 00:00:00'),

('pt-node-26', '网络发送带宽',
 '网络接口发送数据速率（bits/s），排除lo和veth设备',
 '主机监控', '网络', 'node_exporter', 'line',
 'irate(node_network_transmit_bytes_total{instance=~"{{instance}}",device!~"lo|veth.*|docker.*|br-.*"}[5m]) * 8',
 'bps', 'bps', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["network","transmit","bandwidth"]',
 26, '2025-01-01 00:00:00'),

('pt-node-27', '网络包量',
 '网络接口每秒收发数据包数',
 '主机监控', '网络', 'node_exporter', 'line',
 'irate(node_network_receive_packets_total{instance=~"{{instance}}",device!~"lo|veth.*|docker.*|br-.*"}[5m])',
 'pps', 'ops', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":1,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["irate(node_network_transmit_packets_total{instance=~\\"{{instance}}\\",device!~\\"lo|veth.*|docker.*|br-.*\\"}[5m])"]}',
 '["network","packets","pps"]',
 27, '2025-01-01 00:00:00'),

('pt-node-28', '网络错误',
 '网络接口收发错误计数速率',
 '主机监控', '网络', 'node_exporter', 'line',
 'irate(node_network_receive_errs_total{instance=~"{{instance}}",device!~"lo|veth.*|docker.*|br-.*"}[5m])',
 'errors/s', 'ops', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":1,"color":"orange"},{"value":10,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["irate(node_network_transmit_errs_total{instance=~\\"{{instance}}\\",device!~\\"lo|veth.*|docker.*|br-.*\\"}[5m])"]}',
 '["network","errors","health"]',
 28, '2025-01-01 00:00:00'),

('pt-node-29', 'TCP 连接状态',
 '各状态TCP连接数（ESTABLISHED/TIME_WAIT/CLOSE_WAIT等）',
 '主机监控', '网络', 'node_exporter', 'line',
 'node_sockstat_TCP_alloc{instance=~"{{instance}}"}',
 '', 'number', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":0,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["node_sockstat_TCP_tw{instance=~\\"{{instance}}\\"}", "node_sockstat_TCP_inuse{instance=~\\"{{instance}}\\"}"]}',
 '["network","tcp","connections"]',
 29, '2025-01-01 00:00:00'),

('pt-node-30', '网络丢包率',
 '网络接口接收和发送丢包速率',
 '主机监控', '网络', 'node_exporter', 'line',
 'irate(node_network_receive_drop_total{instance=~"{{instance}}",device!~"lo|veth.*|docker.*|br-.*"}[5m])',
 'drops/s', 'ops', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":1,"color":"orange"},{"value":10,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":10,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["irate(node_network_transmit_drop_total{instance=~\\"{{instance}}\\",device!~\\"lo|veth.*|docker.*|br-.*\\"}[5m])"]}',
 '["network","drop","packet_loss"]',
 30, '2025-01-01 00:00:00'),

('pt-node-31', '网络连接数',
 '当前已建立的TCP连接总数',
 '主机监控', '网络', 'node_exporter', 'stat',
 'node_sockstat_TCP_inuse{instance=~"{{instance}}"}',
 '', 'number', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":500,"color":"orange"},{"value":2000,"color":"red"}]}',
 '{"decimals":0,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["network","connections","established"]',
 31, '2025-01-01 00:00:00'),

('pt-node-32', '网络流量总览',
 '网络总接收和发送流量速率（bytes/s），综合概览',
 '主机监控', '网络', 'node_exporter', 'line',
 'sum by(instance)(irate(node_network_receive_bytes_total{instance=~"{{instance}}",device!~"lo|veth.*|docker.*|br-.*"}[5m]))',
 'bytes/s', 'bytes_iec', 12, 4,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"}]}',
 '{"decimals":2,"fillOpacity":20,"showLegend":true,"stackMode":"none","colorMode":"palette","extraQueries":["sum by(instance)(irate(node_network_transmit_bytes_total{instance=~\\"{{instance}}\\",device!~\\"lo|veth.*|docker.*|br-.*\\"}[5m]))"]}',
 '["network","traffic","overview"]',
 32, '2025-01-01 00:00:00'),

-- ============================================================================
-- System (sub_category: '系统', panels 33-40)
-- ============================================================================

('pt-node-33', '系统运行时间',
 '系统自上次启动以来的运行时长（天）',
 '主机监控', '系统', 'node_exporter', 'stat',
 '(time() - node_boot_time_seconds{instance=~"{{instance}}"}) / 86400',
 'days', 'number', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"blue"}]}',
 '{"decimals":1,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"fixed"}',
 '["system","uptime","availability"]',
 33, '2025-01-01 00:00:00'),

('pt-node-34', '进程总数',
 '当前运行中和阻塞的进程总数',
 '主机监控', '系统', 'node_exporter', 'stat',
 'node_procs_running{instance=~"{{instance}}"} + node_procs_blocked{instance=~"{{instance}}"}',
 '', 'number', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":200,"color":"orange"},{"value":500,"color":"red"}]}',
 '{"decimals":0,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["system","processes","total"]',
 34, '2025-01-01 00:00:00'),

('pt-node-35', '文件描述符使用率',
 '已分配文件描述符占系统最大值的百分比',
 '主机监控', '系统', 'node_exporter', 'gauge',
 'node_filefd_allocated{instance=~"{{instance}}"} / node_filefd_maximum{instance=~"{{instance}}"} * 100',
 '%', 'percent', 4, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":70,"color":"orange"},{"value":90,"color":"red"}]}',
 '{"decimals":2,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["system","fd","filehandle"]',
 35, '2025-01-01 00:00:00'),

('pt-node-36', '系统熵',
 '系统可用熵池大小（bits），用于加密随机数生成',
 '主机监控', '系统', 'node_exporter', 'line',
 'node_entropy_available_bits{instance=~"{{instance}}"}',
 'bits', 'number', 6, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"red"},{"value":200,"color":"orange"},{"value":1000,"color":"green"}]}',
 '{"decimals":0,"fillOpacity":15,"showLegend":true,"stackMode":"none","colorMode":"palette"}',
 '["system","entropy","security"]',
 36, '2025-01-01 00:00:00'),

('pt-node-37', '系统信息',
 '主机系统信息概览，包括主机名、内核版本、架构等',
 '主机监控', '系统', 'node_exporter', 'table',
 'node_uname_info{instance=~"{{instance}}"}',
 '', 'none', 12, 3,
 '{"mode":"absolute","steps":[{"value":0,"color":"blue"}]}',
 '{"decimals":0,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"fixed","columns":["nodename","sysname","release","machine","instance"]}',
 '["system","info","uname"]',
 37, '2025-01-01 00:00:00'),

('pt-node-38', '启动时间',
 '系统上次启动的时间戳',
 '主机监控', '系统', 'node_exporter', 'stat',
 'node_boot_time_seconds{instance=~"{{instance}}"}',
 'datetime', 'datetime', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"blue"}]}',
 '{"decimals":0,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"fixed"}',
 '["system","boot","time"]',
 38, '2025-01-01 00:00:00'),

('pt-node-39', '运行进程数',
 '当前处于运行状态的进程数',
 '主机监控', '系统', 'node_exporter', 'stat',
 'node_procs_running{instance=~"{{instance}}"}',
 '', 'number', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":50,"color":"orange"},{"value":150,"color":"red"}]}',
 '{"decimals":0,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["system","procs","running"]',
 39, '2025-01-01 00:00:00'),

('pt-node-40', '阻塞进程数',
 '当前处于阻塞状态（等待I/O）的进程数',
 '主机监控', '系统', 'node_exporter', 'stat',
 'node_procs_blocked{instance=~"{{instance}}"}',
 '', 'number', 3, 2,
 '{"mode":"absolute","steps":[{"value":0,"color":"green"},{"value":5,"color":"orange"},{"value":20,"color":"red"}]}',
 '{"decimals":0,"fillOpacity":0,"showLegend":false,"stackMode":"none","colorMode":"thresholds"}',
 '["system","procs","blocked"]',
 40, '2025-01-01 00:00:00');
