-- ============================================================
-- V7_11: PostgreSQL 监控面板模板 (16条)
-- 覆盖: 连接 / 查询 / 锁 / 复制 / 表 / 缓存
-- ============================================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type,
     chart_type, promql, unit, unit_format,
     default_width, default_height, thresholds, options, tags, sort_order, created_at)
VALUES

-- ===================== 连接 (3) =====================

('pt-pg-01',
 '活跃连接数',
 'PostgreSQL 当前活跃（state=active）的连接数，持续高位可能导致连接池耗尽',
 'PostgreSQL', '连接', 'postgres_exporter',
 'gauge',
 'sum(pg_stat_activity_count{state="active",instance=~"{{instance}}"})',
 'count', 'short',
 3, 3,
 '{"warning": 50, "critical": 100}',
 '{"decimals": 0, "minValue": 0, "maxValue": 200, "thresholdMode": "absolute"}',
 '["postgresql", "connections", "active"]',
 1, '2025-01-01 00:00:00'),

('pt-pg-02',
 '空闲连接数',
 'PostgreSQL 当前空闲（state=idle）的连接数，过多空闲连接浪费资源',
 'PostgreSQL', '连接', 'postgres_exporter',
 'stat',
 'sum(pg_stat_activity_count{state="idle",instance=~"{{instance}}"})',
 'count', 'short',
 3, 2,
 '{"warning": 80, "critical": 150}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["postgresql", "connections", "idle"]',
 2, '2025-01-01 00:00:00'),

('pt-pg-03',
 '连接使用率',
 '当前总连接数占 max_connections 的百分比，超过 80% 需要考虑扩容或优化连接池',
 'PostgreSQL', '连接', 'postgres_exporter',
 'gauge',
 'sum(pg_stat_activity_count{instance=~"{{instance}}"}) / pg_settings_max_connections{instance=~"{{instance}}"} * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 70, "critical": 90}',
 '{"decimals": 1, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["postgresql", "connections", "usage"]',
 3, '2025-01-01 00:00:00'),

-- ===================== 查询 (4) =====================

('pt-pg-04',
 '每秒事务数 (QPS)',
 '每秒提交和回滚的事务总数，反映数据库整体吞吐量',
 'PostgreSQL', '查询', 'postgres_exporter',
 'line',
 'sum by (datname) (rate(pg_stat_database_xact_commit{instance=~"{{instance}}",datname=~"{{database}}"}[5m]) + rate(pg_stat_database_xact_rollback{instance=~"{{instance}}",datname=~"{{database}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "TPS", "fillOpacity": 15}',
 '["postgresql", "query", "tps"]',
 4, '2025-01-01 00:00:00'),

('pt-pg-05',
 '慢查询数量',
 '当前执行时间超过 1 秒的活跃查询数，持续存在需要优化 SQL 或添加索引',
 'PostgreSQL', '查询', 'postgres_exporter',
 'stat',
 'sum(pg_stat_activity_count{state="active",instance=~"{{instance}}"} and on(pid) pg_stat_activity_max_tx_duration{instance=~"{{instance}}"} > 1)',
 'count', 'short',
 3, 2,
 '{"warning": 3, "critical": 10}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["postgresql", "query", "slow"]',
 5, '2025-01-01 00:00:00'),

('pt-pg-06',
 '事务提交速率',
 '每秒事务提交数，按数据库分组',
 'PostgreSQL', '查询', 'postgres_exporter',
 'line',
 'sum by (datname) (rate(pg_stat_database_xact_commit{instance=~"{{instance}}",datname=~"{{database}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Commits/s", "fillOpacity": 10}',
 '["postgresql", "query", "commit"]',
 6, '2025-01-01 00:00:00'),

('pt-pg-07',
 '事务回滚速率',
 '每秒事务回滚数，持续高回滚率可能存在应用逻辑问题或锁冲突',
 'PostgreSQL', '查询', 'postgres_exporter',
 'line',
 'sum by (datname) (rate(pg_stat_database_xact_rollback{instance=~"{{instance}}",datname=~"{{database}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{"warning": 5, "critical": 20}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Rollbacks/s", "fillOpacity": 10}',
 '["postgresql", "query", "rollback"]',
 7, '2025-01-01 00:00:00'),

-- ===================== 锁 (2) =====================

('pt-pg-08',
 '锁按类型分布',
 '按锁模式（AccessShare、RowExclusive 等）分组统计当前持有的锁数量',
 'PostgreSQL', '锁', 'postgres_exporter',
 'line',
 'sum by (mode) (pg_locks_count{instance=~"{{instance}}"})',
 'count', 'short',
 6, 3,
 '{"warning": 50, "critical": 200}',
 '{"legend": true, "stacked": true, "decimals": 0, "yAxisLabel": "Locks", "fillOpacity": 30}',
 '["postgresql", "locks", "mode"]',
 8, '2025-01-01 00:00:00'),

('pt-pg-09',
 '死锁数',
 '数据库累计发生的死锁次数，任何死锁都需要关注并排查 SQL 执行顺序',
 'PostgreSQL', '锁', 'postgres_exporter',
 'stat',
 'sum by (datname) (pg_stat_database_deadlocks{instance=~"{{instance}}",datname=~"{{database}}"})',
 'count', 'short',
 3, 2,
 '{"warning": 1, "critical": 5}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["postgresql", "locks", "deadlock"]',
 9, '2025-01-01 00:00:00'),

-- ===================== 复制 (3) =====================

('pt-pg-10',
 '复制延迟',
 '主从复制延迟时间，延迟过大会导致从库读取到过期数据',
 'PostgreSQL', '复制', 'postgres_exporter',
 'gauge',
 'pg_replication_lag{instance=~"{{instance}}"}',
 's', 'duration',
 3, 3,
 '{"warning": 5, "critical": 30}',
 '{"decimals": 2, "minValue": 0, "maxValue": 60, "thresholdMode": "absolute"}',
 '["postgresql", "replication", "lag"]',
 10, '2025-01-01 00:00:00'),

('pt-pg-11',
 'WAL 大小',
 'WAL 日志的当前 LSN 位移差值，反映 WAL 生成速率和堆积情况',
 'PostgreSQL', '复制', 'postgres_exporter',
 'line',
 'pg_wal_lsn_diff{instance=~"{{instance}}"}',
 'bytes', 'bytes_iec',
 6, 3,
 '{"warning": 1073741824, "critical": 4294967296}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "WAL Size", "fillOpacity": 15}',
 '["postgresql", "replication", "wal"]',
 11, '2025-01-01 00:00:00'),

('pt-pg-12',
 '从节点数',
 '当前连接的流复制从节点数量，少于预期说明有从库断连',
 'PostgreSQL', '复制', 'postgres_exporter',
 'stat',
 'count(pg_stat_replication_backend_xmin{instance=~"{{instance}}"})',
 'count', 'short',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["postgresql", "replication", "slaves"]',
 12, '2025-01-01 00:00:00'),

-- ===================== 表 (2) =====================

('pt-pg-13',
 '死元组数 TOP10',
 '按表维度聚合死元组数量，展示 TOP10，死元组过多需要执行 VACUUM',
 'PostgreSQL', '表', 'postgres_exporter',
 'bar',
 'topk(10, sum by (relname) (pg_stat_user_tables_n_dead_tup{instance=~"{{instance}}"}))',
 'count', 'short',
 6, 3,
 '{"warning": 100000, "critical": 1000000}',
 '{"legend": true, "orientation": "horizontal", "showValue": true, "decimals": 0}',
 '["postgresql", "table", "dead_tuples"]',
 13, '2025-01-01 00:00:00'),

('pt-pg-14',
 '顺序扫描速率',
 '每秒全表顺序扫描次数，频繁顺序扫描可能缺少合适的索引',
 'PostgreSQL', '表', 'postgres_exporter',
 'line',
 'sum by (relname) (rate(pg_stat_user_tables_seq_scan{instance=~"{{instance}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{"warning": 10, "critical": 50}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Seq Scans/s", "fillOpacity": 10}',
 '["postgresql", "table", "seq_scan"]',
 14, '2025-01-01 00:00:00'),

-- ===================== 缓存 (2) =====================

('pt-pg-15',
 '缓存命中率',
 '共享缓冲区命中率，低于 99% 需考虑增加 shared_buffers 或优化查询',
 'PostgreSQL', '缓存', 'postgres_exporter',
 'gauge',
 'sum(pg_stat_database_blks_hit{instance=~"{{instance}}",datname=~"{{database}}"}) / (sum(pg_stat_database_blks_hit{instance=~"{{instance}}",datname=~"{{database}}"}) + sum(pg_stat_database_blks_read{instance=~"{{instance}}",datname=~"{{database}}"})) * 100',
 '%', 'percent',
 3, 3,
 '{"warning": 95, "critical": 90}',
 '{"decimals": 2, "minValue": 0, "maxValue": 100, "thresholdMode": "percentage"}',
 '["postgresql", "cache", "hit_rate"]',
 15, '2025-01-01 00:00:00'),

('pt-pg-16',
 '共享缓冲区读写量',
 '共享缓冲区每秒块读取和命中的速率变化，反映 IO 压力趋势',
 'PostgreSQL', '缓存', 'postgres_exporter',
 'line',
 'sum by (datname) (rate(pg_stat_database_blks_read{instance=~"{{instance}}",datname=~"{{database}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{"warning": 100, "critical": 500}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Blocks Read/s", "fillOpacity": 15}',
 '["postgresql", "cache", "blocks"]',
 16, '2025-01-01 00:00:00');
