-- ============================================================
-- V7_10: Kafka 监控面板模板 (14条)
-- 覆盖: Broker / Topic / 消费者组 / 生产者
-- ============================================================

INSERT IGNORE INTO prom_panel_template
    (id, name, description, category, sub_category, exporter_type,
     chart_type, promql, unit, unit_format,
     default_width, default_height, thresholds, options, tags, sort_order, created_at)
VALUES

-- ===================== Broker (4) =====================

('pt-kafka-01',
 'Broker 分区数',
 '每个 Broker 上的分区总数，不均衡说明需要重新分配分区',
 'Kafka', 'Broker', 'kafka_exporter',
 'stat',
 'sum(kafka_broker_info{instance=~"{{instance}}"}) by (instance)',
 'count', 'short',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["kafka", "broker", "partitions"]',
 1, '2025-01-01 00:00:00'),

('pt-kafka-02',
 'Leader 分区数',
 '每个 Broker 上的 Leader 分区数量，过度集中会导致热点问题',
 'Kafka', 'Broker', 'kafka_exporter',
 'stat',
 'count(kafka_topic_partition_leader{instance=~"{{instance}}"}) by (instance)',
 'count', 'short',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "area", "reduceCalc": "lastNotNull"}',
 '["kafka", "broker", "leader"]',
 2, '2025-01-01 00:00:00'),

('pt-kafka-03',
 'ISR 收缩分区数',
 '处于副本不足状态的分区数，大于 0 表示存在副本同步问题',
 'Kafka', 'Broker', 'kafka_exporter',
 'line',
 'sum(kafka_topic_partition_under_replicated_partition{instance=~"{{instance}}"}) by (topic)',
 'count', 'short',
 6, 3,
 '{"warning": 1, "critical": 5}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Under Replicated", "fillOpacity": 10}',
 '["kafka", "broker", "isr"]',
 3, '2025-01-01 00:00:00'),

('pt-kafka-04',
 '活跃控制器数',
 '集群中活跃 Controller 的数量，正常情况下应始终为 1',
 'Kafka', 'Broker', 'kafka_exporter',
 'stat',
 'sum(kafka_controller_active_controller_count{instance=~"{{instance}}"})',
 'count', 'short',
 3, 2,
 '{"warning": 0, "critical": 2}',
 '{"colorMode": "background", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["kafka", "broker", "controller"]',
 4, '2025-01-01 00:00:00'),

-- ===================== Topic (3) =====================

('pt-kafka-05',
 '消息速率',
 'Topic 每秒产生的消息数，通过 Offset 变化率计算',
 'Kafka', 'Topic', 'kafka_exporter',
 'line',
 'sum by (topic) (rate(kafka_topic_partition_current_offset{instance=~"{{instance}}",topic=~"{{topic}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Messages/s", "fillOpacity": 15}',
 '["kafka", "topic", "messages"]',
 5, '2025-01-01 00:00:00'),

('pt-kafka-06',
 'Topic 字节流入速率',
 '每个 Topic 每秒写入的字节数，反映写入压力',
 'Kafka', 'Topic', 'kafka_exporter',
 'line',
 'sum by (topic) (rate(kafka_server_brokertopicmetrics_bytesin_total{instance=~"{{instance}}",topic=~"{{topic}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 52428800, "critical": 104857600}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Bytes In/s", "fillOpacity": 15}',
 '["kafka", "topic", "bytes_in"]',
 6, '2025-01-01 00:00:00'),

('pt-kafka-07',
 'Topic 字节流出速率',
 '每个 Topic 每秒读取的字节数，反映消费端拉取压力',
 'Kafka', 'Topic', 'kafka_exporter',
 'line',
 'sum by (topic) (rate(kafka_server_brokertopicmetrics_bytesout_total{instance=~"{{instance}}",topic=~"{{topic}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 52428800, "critical": 104857600}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Bytes Out/s", "fillOpacity": 15}',
 '["kafka", "topic", "bytes_out"]',
 7, '2025-01-01 00:00:00'),

-- ===================== 消费者组 (4) =====================

('pt-kafka-08',
 '消费者 Lag',
 '消费者组在各分区上的消息积压量，Lag 持续增长表示消费速度跟不上生产速度',
 'Kafka', '消费者组', 'kafka_exporter',
 'line',
 'sum by (consumergroup, topic) (kafka_consumergroup_lag{instance=~"{{instance}}",consumergroup=~"{{consumergroup}}"})',
 'count', 'short',
 6, 3,
 '{"warning": 1000, "critical": 10000}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Lag", "fillOpacity": 10}',
 '["kafka", "consumer", "lag"]',
 8, '2025-01-01 00:00:00'),

('pt-kafka-09',
 '消费组 Offset',
 '消费者组当前消费到的 Offset 位置，持续不变说明消费停滞',
 'Kafka', '消费者组', 'kafka_exporter',
 'line',
 'sum by (consumergroup, topic) (kafka_consumergroup_current_offset{instance=~"{{instance}}",consumergroup=~"{{consumergroup}}"})',
 'count', 'short',
 6, 3,
 '{}',
 '{"legend": true, "stacked": false, "decimals": 0, "yAxisLabel": "Offset", "fillOpacity": 10}',
 '["kafka", "consumer", "offset"]',
 9, '2025-01-01 00:00:00'),

('pt-kafka-10',
 '消费者 Lag TOP10',
 '按消费者组维度聚合，展示 Lag 总量最大的 TOP10 消费组',
 'Kafka', '消费者组', 'kafka_exporter',
 'bar',
 'topk(10, sum by (consumergroup) (kafka_consumergroup_lag{instance=~"{{instance}}"}))',
 'count', 'short',
 6, 3,
 '{"warning": 5000, "critical": 50000}',
 '{"legend": true, "orientation": "horizontal", "showValue": true, "decimals": 0}',
 '["kafka", "consumer", "lag", "top"]',
 10, '2025-01-01 00:00:00'),

('pt-kafka-11',
 '消费组数量',
 '当前注册的消费者组总数',
 'Kafka', '消费者组', 'kafka_exporter',
 'stat',
 'count(count by (consumergroup) (kafka_consumergroup_current_offset{instance=~"{{instance}}"}))',
 'count', 'short',
 3, 2,
 '{}',
 '{"colorMode": "value", "textMode": "value", "graphMode": "none", "reduceCalc": "lastNotNull"}',
 '["kafka", "consumer", "groups"]',
 11, '2025-01-01 00:00:00'),

-- ===================== 生产者 (3) =====================

('pt-kafka-12',
 '请求速率',
 'Broker 每秒收到的 Produce 请求数，反映生产者的写入频率',
 'Kafka', '生产者', 'kafka_exporter',
 'line',
 'sum by (instance) (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~"{{instance}}"}[5m]))',
 'ops', 'short',
 6, 3,
 '{}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Requests/s", "fillOpacity": 10}',
 '["kafka", "producer", "requests"]',
 12, '2025-01-01 00:00:00'),

('pt-kafka-13',
 '字节流入速率',
 'Broker 每秒接收到的全部字节数（所有 Topic 合计），反映整体写入带宽',
 'Kafka', '生产者', 'kafka_exporter',
 'line',
 'sum by (instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{instance=~"{{instance}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 104857600, "critical": 524288000}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Bytes In/s", "fillOpacity": 15}',
 '["kafka", "producer", "bytes"]',
 13, '2025-01-01 00:00:00'),

('pt-kafka-14',
 '网络 IO 速率',
 'Broker 网络层收发的字节速率，衡量 Kafka 整体网络 IO 负载',
 'Kafka', '生产者', 'kafka_exporter',
 'line',
 'sum by (instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{instance=~"{{instance}}"}[5m]) + rate(kafka_server_brokertopicmetrics_bytesout_total{instance=~"{{instance}}"}[5m]))',
 'Bps', 'bytes_iec',
 6, 3,
 '{"warning": 209715200, "critical": 1048576000}',
 '{"legend": true, "stacked": false, "decimals": 2, "yAxisLabel": "Network IO/s", "fillOpacity": 15}',
 '["kafka", "network", "io"]',
 14, '2025-01-01 00:00:00');
